name: novenio
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  ioc_container: ^1.0.12
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
